import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import NavBar from '@/components/Navbar';
import { JamProvider } from '@/components/JamsContext';
import Providers from './providers';

// Load Poppins font with specific weights
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Musicians of Manoa',
  description: 'Generated by ics-software-engineering.github.io',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const classString = `${poppins.className} wrapper`;
  return (
    <html lang="en">
      <body className={classString}>
        <JamProvider>
          <Providers>
            <NavBar />
            {children}
          </Providers>
        </JamProvider>
      </body>
    </html>
  );
}
