name: ci-musicians-of-manoa
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
env:
  NEXTAUTH_URL: http://localhost:3000
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  DATABASE_URL: ${{ vars.DATABASE_URL }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
      - name: Print environment variables
        run: |
          echo "NEXTAUTH_URL: $NEXTAUTH_URL"
          echo "DATABASE_URL: $DATABASE_URL"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Verify Playwright Installation
        run: npx playwright --version
      - name: Run ESLint with detailed output
        run: npm run lint || true
      - name: Run Playwright tests
        run: |
          npx playwright show-report
          cat playwright-report/index.html
